// Demo Users for Authentication
export const demoUsers = [
  {
    id: 'admin1',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@edupulse.in',
    password: 'Admin@123',
    role: 'admin',
  },
  {
    id: 'teacher1',
    name: 'Dr. Priya Sharma',
    email: 'priya.sharma@edupulse.in',
    password: 'Teacher@123',
    role: 'teacher',
  },
  {
    id: 'teacher2',
    name: 'Arun Patel',
    email: 'arun.patel@edupulse.in',
    password: 'Teacher@123',
    role: 'teacher',
  },
  {
    id: 'student1',
    name: 'Arjun Singh',
    email: 'arjun.singh@edupulse.in',
    password: 'Student@123',
    role: 'student',
  },
  {
    id: 'student2',
    name: 'Neha Gupta',
    email: 'neha.gupta@edupulse.in',
    password: 'Student@123',
    role: 'student',
  },
];

// Mock Data for EduPulse AI
export const mockTeachers = [
  {
    id: 't1',
    name: 'Dr. Priya Sharma',
    subject: 'Mathematics',
    onTopicPercentage: 82,
    totalSessions: 45,
    averageEngagement: 78,
    status: 'Exemplary',
    curriculumCovered: 95,
    lastSession: '2026-01-05',
    trends: [
      { date: 'Jan 1', percentage: 78 },
      { date: 'Jan 2', percentage: 80 },
      { date: 'Jan 3', percentage: 79 },
      { date: 'Jan 4', percentage: 82 },
      { date: 'Jan 5', percentage: 82 },
    ],
  },
  {
    id: 't2',
    name: 'Arun Patel',
    subject: 'English Literature',
    onTopicPercentage: 68,
    totalSessions: 42,
    averageEngagement: 65,
    status: 'Needs Improvement',
    curriculumCovered: 72,
    lastSession: '2026-01-05',
    trends: [
      { date: 'Jan 1', percentage: 65 },
      { date: 'Jan 2', percentage: 66 },
      { date: 'Jan 3', percentage: 67 },
      { date: 'Jan 4', percentage: 68 },
      { date: 'Jan 5', percentage: 68 },
    ],
  },
  {
    id: 't3',
    name: 'Ms. Anjali Verma',
    subject: 'Science',
    onTopicPercentage: 88,
    totalSessions: 48,
    averageEngagement: 85,
    status: 'Exemplary',
    curriculumCovered: 98,
    lastSession: '2026-01-05',
    trends: [
      { date: 'Jan 1', percentage: 84 },
      { date: 'Jan 2', percentage: 86 },
      { date: 'Jan 3', percentage: 87 },
      { date: 'Jan 4', percentage: 88 },
      { date: 'Jan 5', percentage: 88 },
    ],
  },
];

export const mockStudents = [
  {
    id: 's1',
    name: 'Arjun Singh',
    grade: '10A',
    attendancePercentage: 94,
    engagementPercentage: 87,
    status: 'Active',
    interestLevels: {
      'Mathematics': 85,
      'Science': 72,
      'English': 60,
      'History': 55,
      'Art': 68,
    },
    futureCapability: ['Engineer', 'Mathematician', 'Data Scientist'],
    lastAttended: '2026-01-05',
  },
  {
    id: 's2',
    name: 'Neha Gupta',
    grade: '10A',
    attendancePercentage: 89,
    engagementPercentage: 76,
    status: 'Active',
    interestLevels: {
      'Mathematics': 65,
      'Science': 88,
      'English': 72,
      'History': 70,
      'Art': 55,
    },
    futureCapability: ['Biologist', 'Chemist', 'Environmental Scientist'],
    lastAttended: '2026-01-05',
  },
  {
    id: 's3',
    name: 'Vikram Reddy',
    grade: '10A',
    attendancePercentage: 92,
    engagementPercentage: 81,
    status: 'Active',
    interestLevels: {
      'Mathematics': 75,
      'Science': 80,
      'English': 78,
      'History': 85,
      'Art': 88,
    },
    futureCapability: ['Historian', 'Artist', 'Architect'],
    lastAttended: '2026-01-05',
  },
  {
    id: 's4',
    name: 'Priya Desai',
    grade: '10A',
    attendancePercentage: 71,
    engagementPercentage: 62,
    status: 'At Risk',
    interestLevels: {
      'Mathematics': 45,
      'Science': 50,
      'English': 68,
      'History': 72,
      'Art': 70,
    },
    futureCapability: ['Writer', 'Journalist', 'Teacher'],
    lastAttended: '2026-01-04',
  },
  {
    id: 's5',
    name: 'Ravi Mehta',
    grade: '10A',
    attendancePercentage: 96,
    engagementPercentage: 93,
    status: 'Active',
    interestLevels: {
      'Mathematics': 92,
      'Science': 89,
      'English': 85,
      'History': 80,
      'Art': 75,
    },
    futureCapability: ['Doctor', 'Engineer', 'Research Scientist'],
    lastAttended: '2026-01-05',
  },
];

export const mockClassAnalytics = {
  currentLecture: {
    topic: 'Quadratic Equations',
    subject: 'Mathematics',
    duration: 45,
    onTopic: 37,
    offTopic: 8,
    topicBreakdown: [
      { topic: 'Quadratic Equations', value: 37, fill: '#059669' },
      { topic: 'Off-Topic', value: 8, fill: '#ef4444' },
    ],
  },
  studentInterest: [
    { topic: 'Quadratic Equations', interest: 85 },
    { topic: 'Factorization', interest: 78 },
    { topic: 'Graphing', interest: 72 },
    { topic: 'Applications', interest: 68 },
    { topic: 'Problem Solving', interest: 80 },
  ],
  engagementByStudent: [
    { studentId: 's1', name: 'Alex Thompson', engagement: 92, futureCapability: 95 },
    { studentId: 's2', name: 'Jordan Lee', engagement: 65, futureCapability: 62 },
    { studentId: 's3', name: 'Casey Martinez', engagement: 78, futureCapability: 72 },
    { studentId: 's4', name: 'Morgan Davis', engagement: 45, futureCapability: 35 },
    { studentId: 's5', name: 'Taylor White', engagement: 95, futureCapability: 98 },
  ],
};

export const mockSystemReport = {
  totalTeachers: 3,
  exemplaryTeachers: 2,
  needsImprovementTeachers: 1,
  totalStudents: 5,
  activeStudents: 4,
  atRiskStudents: 1,
  averageTeacherQuality: 79.33,
  averageStudentEngagement: 81.4,
  classesProductive: 2,
  classesNeedImprovement: 1,
  trends: [
    { week: 'Week 1', quality: 76, engagement: 78 },
    { week: 'Week 2', quality: 77, engagement: 79 },
    { week: 'Week 3', quality: 78, engagement: 80 },
    { week: 'Week 4', quality: 79, engagement: 81 },
    { week: 'Week 5', quality: 79, engagement: 82 },
  ],
};

export const mockAlerts = [
  {
    id: 'a1',
    type: 'teacher',
    severity: 'medium',
    message: 'Mr. James Wilson is below 75% on-topic threshold',
    target: 't2',
    timestamp: '2026-01-05T14:30:00Z',
  },
  {
    id: 'a2',
    type: 'student',
    severity: 'high',
    message: 'Morgan Davis attendance at risk (71%)',
    target: 's4',
    timestamp: '2026-01-05T13:15:00Z',
  },
];
